# Generated by Django 5.1.2 on 2024-10-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
        ('posts', '0002_post_author'),
    ]

    operations = [
    ]
