# Generated by Django 5.1.2 on 2024-10-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_merge_0002_alter_post_image_0002_post_author'),
        ('posts', '0003_post_category'),
    ]

    operations = [
    ]
