# Generated by Django 5.1.2 on 2024-10-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0002_reclamation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
