# Generated by Django 5.1.2 on 2024-10-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0003_reclamation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved'), ('not_accepted', 'Not Accepted')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reclamations.reclamation')),
            ],
        ),
    ]
