# Generated by Django 4.1 on 2024-10-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
