# Generated by Django 5.1.2 on 2024-10-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatgroup_is_private_chatgroup_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
