# Generated by Django 5.1.2 on 2024-10-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatgroup_admin_chatgroup_groupchat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='groupchat_name',
        ),
    ]
